### ISSUE TITLE
Social Media Assets

### ISSUE THREAD

**Issue by ahmadnassri** [functions-conf/brand#7]
require assets that show the following:
- event logo (Functions & ServerlessDays)
- date
- location 
- link to website: `https://functions.events/2018/toronto`

require the following variants:

- [x] [Eventbrite banner](https://www.eventbrite.com/support/articles/en_US/Troubleshooting/how-to-choose-a-great-event-image?lg=en_US)
- [x] [Twitter Card](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image.html)
- [x] [Facebook Open Graph](https://developers.facebook.com/docs/sharing/best-practices#images)

**Comment by briancormier** [comment]
I'll have this done today, estimating 3 hours of work
